### ISSUE TITLE
[Bug]: error log when obcdc normal launch

### ISSUE THREAD

**Issue by nautaa** [oceanbase/oceanbase#1907] opened 2024-04-01 09:59 UTC
**Describe the bug**

when obcdc normal launch, there are some unexpected error logs.
```
[2024-04-01 17:44:30.733964] WDIAG get (ob_config_helper.cpp:694) [27945][][T0][Y0-0000000000000000-0-0] [lt=401][errcode=-4016] set time error(str=" ", p_unit=" ")
[2024-04-01 17:44:30.733984] ERROR [LIB] issue_dba_error (ob_log.cpp:1987) [27945][][T0][Y0-0000000000000000-0-0] [lt=18][errcode=-4388] Unexpected internal error happen, please checkout the internal errcode(errcode=-4016, file="ob_config.cpp", line_no=657, info="set time error")
```
A similar issue was fixed in #1786 
you can refer PR #1826 to try to fix this issue.

**Environment**

- OS Version and CPU Arch(`uname -a`):
  
- OB Version(`LD_LIBRARY_PATH=../lib:$LD_LIBRARY_PATH ./observer -V`):
  

**Fast Reproduce Steps(Required)**

launch obcdc and watch log files.

**Expected behavior**

Find out where the error log is being caused and fix it

**Actual Behavior**

**Additional context**

fix it in develop branch.

**Comment by nautaa** [comment] 2024-04-11 02:59
@zztaki comment here, i will assign you.

**Comment by zztaki** [comment] 2024-04-11 03:00
> @zztaki comment here, i will assign you.

please assign to me. :)

**Comment by zztaki** [comment] 2024-04-11 13:48
@nautaa sry, I can't reproduce it in `develop` branch.
After `./tools/deploy/obd.sh prepare -p ...` and `./tools/deploy/obd.sh deploy -c ./tools/deploy/single.yaml`, I do ` ./obcdc_tailf -f /path/to/libobcdc.conf` on `/path/to/oceanbase/build_debug/src/logservice/libobcdc/tests`.

**Comment by zztaki** [comment] 2024-04-11 13:49
[libobcdc.log](https://github.com/oceanbase/oceanbase/files/14946932/libobcdc.log)
this is my log.

**Comment by zztaki** [comment] 2024-04-11 13:54
But I find this Error in `oblogminer.log` from `oblogminer`'s result.

**Comment by nautaa** [comment] 2024-04-11 13:55
> But I find this Error in `oblogminer.log` from `oblogminer`'s result.

use 4.2.x branch?

**Comment by zztaki** [comment] 2024-04-11 13:56
> > But I find this Error in `oblogminer.log` from `oblogminer`'s result.
> 
> use 4.2.x branch?

[2024-04-10 10:35:24.172449] WDIAG get (ob_config_helper.cpp:579) [190504][][T0][Y0-0000000000000000-0-0] [lt=10][errcode=-4016] set int error(str=" ", valid=false)
[2024-04-10 10:35:24.172480] ERROR [LIB] issue_dba_error (ob_log.cpp:1987) [190504][][T0][Y0-0000000000000000-0-0] [lt=16][errcode=-4388] Unexpected internal error happen, please checkout the internal errcode(errcode=-4016, file="ob_config.cpp", line_no=698, info="set int error")

**Comment by nautaa** [comment] 2024-04-12 02:24
@zztaki i found obcdc_tailf is not set log file before this error log, so you can reproduce use oblogminer. the related code in `4.2.x` and `develop` is same. reproduce it in `4.2.x` and fix in `develop`. sorry for the confusion.

**Comment by nautaa** [comment] 2024-04-12 02:25
> > > But I find this Error in `oblogminer.log` from `oblogminer`'s result.
> > 
> > 
> > use 4.2.x branch?
> 
> ```c++
> [2024-04-10 10:35:24.172449] WDIAG get (ob_config_helper.cpp:579) [190504][][T0][Y0-0000000000000000-0-0] [lt=10][errcode=-4016] set int error(str=" ", valid=false)
> [2024-04-10 10:35:24.172480] ERROR [LIB] issue_dba_error (ob_log.cpp:1987) [190504][][T0][Y0-0000000000000000-0-0] [lt=16][errcode=-4388] Unexpected internal error happen, please checkout the internal errcode(errcode=-4016, file="ob_config.cpp", line_no=698, info="set int error")
> ```
> 
> Yes, this was my previous log.

there should be another error log that "set time error".

**Comment by zztaki** [comment] 2024-04-12 11:00
@nautaa Thank you for your help. :)

**Comment by nautaa** [comment] 2024-04-29 12:22
It's ok, Thanks for your previous contributions! Go do what's more important to you! If interested in open source contributions, keep in touch. :)

**Closed** 2024-06-03 02:24 UTC
Labels: type: bug, good first issue, help wanted
