### ISSUE TITLE
为什么代码都没有注释呢？

### ISSUE THREAD

**Issue by ahdong2007** [oceanbase/oceanbase#100] opened 2021-06-12 11:21 UTC
这么大一个项目，300w行代码，几乎没有注释，不太友好吧。

**Comment by longdafeng** [comment] 2021-06-14 11:08
Thanks for your feedback.

We have removed a lot of Chinese Comments during the course of opening source code. Most of the Chinese Comments is pretty hard to translate, at the same time, we have no enough time to translate them.   So this is the root cause. 

We will add comments as time goes on.

Any contribution are appreciated, if you can add comments, that will be wonderful.

**Comment by zeminzhou** [comment] 2021-06-16 09:26
What are the requirements for the format of comments?

**Comment by MizuhaHimuraki** [comment] 2021-06-17 06:38
Duplicate of #6

**Closed by MizuhaHimuraki** 2021-06-17 06:38 UTC
