### ISSUE TITLE
[Feature]: Add a configuration item to determine whether to enable "lock in share mode"

### ISSUE THREAD

**Issue by netluo** [oceanbase/oceanbase#1442] opened 2023-06-19 03:12 UTC
**Use Case**
The current "lock in share mode" syntax is implemented by simulating Mutual exclusion, which has certain restrictions on use.
To avoid unexpected errors in the use of this feature by users who are not familiar with it, a configuration item should be added to confirm whether it is enabled.

**Describe the solution you'd like**
When this syntax is not enabled, a Syntax error will be prompted when using this syntax, and the prompt configuration item should be enabled if using this syntax. Please check the official website for configuration details.
**Describe alternatives you've considered**

**Additional context**

**Comment by dimstars** [comment] 2023-06-19 03:34
The need has been confirmed and we are moving forward. The current progress is as follows:

- [ ] 1. Demand Confirmation

We think this feature is necessary to avoid unexpected problems when using "lock in share mode".

- [ ] 2. Configuration item approval

The approval process is in progress.

> The configuration item approval process is proposed by OceanBase internal personnel. Configuration items can only be added after approval by the person in charge.

- [ ] 3. Design proposal

to be designed

- [ ] 4. Code implementation

To be realized

- [ ] 5. Functional verification

to be tested

- [ ] 6. Code integration

to be merged

**Comment by dimstars** [comment] 2023-06-27 02:07
Unfortunately, the request for additional parameters was rejected. Because this parameter does not have sufficient necessity. Grammatical restrictions can be documented without an additional parameter. In addition, the above scenarios occur less frequently and do not affect correctness. So this issue will be shelved. Thank you for your understanding!

**Closed** 2023-06-28 01:33 UTC
Labels: type: feature, status: confirmed, status: won't fix, module: transaction
