### ISSUE TITLE
Ubuntu plz

### ISSUE THREAD

**Issue by zepc007** [oceanbase/oceanbase#21] opened 2021-06-01 05:40 UTC

**Comment by MizuhaHimuraki** [comment] 2021-06-01 06:00
Thanks for your feedback.

Workaround, see #3

**Comment by ethan-tqa** [comment] 2021-06-02 03:00
Considering that Ubuntu is a major distribution used in many cloud servers, it would be good to have support for Ubuntu.

**Comment by MizuhaHimuraki** [comment] 2021-06-02 09:49
duplicate of #56

**Closed by MizuhaHimuraki** 2021-06-02 09:49 UTC
