### ISSUE TITLE
is compatible with ORACLE protocol and syntax？

### ISSUE THREAD

**Issue by agui001** [oceanbase/oceanbase#72] opened 2021-06-04 01:39 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lemon0910** [comment] 2021-06-04 01:47
same question. see[question](https://github.com/oceanbase/oceanbase/issues/48)

**Comment by MizuhaHimuraki** [comment] 2021-06-04 03:17
Duplicate of #48

**Closed** 2021-06-04 03:17 UTC
