### ISSUE TITLE
Ob单机版安装失败，一直卡在最后一步

### ISSUE THREAD

**Issue by SilvaXiang** [oceanbase/oceanbase#73] opened 2021-06-04 02:49 UTC
安装Ob单机版（中控和目标机器在一个机器上），按照步骤来的
最后一步一直失败
![image](https://user-images.githubusercontent.com/22973642/120738176-fa5e2a80-c521-11eb-97f5-cece46328717.png)
Observer.log搜索Error的地方也就这几处
`[2021-6-2 13:49:0.65497] INFO [cut@ob_memory_cutter.cpp:131] [3441][Y7369676E616C-0] free_chunk, freed: 0
CRASH ERROR!!! sig=6, sig_code=-6, sig_addr=ac3, timestamp=1622641740065385, tid=3281, tname=MultiTenant, trace_id=0-0, extra_info=((null)), lbt=0x90af028 0x90b0076 0x7f2b9868962f 0x7f2b97fe0387 0x7f2b97fe1a77 0x92925aa 0x92904b7 0x9291c3a 0x8ee80c1 0x8eb5429 0x2a50561 0x8a5b4ee 0x8a5b878 0x8a449cb 0x8a44133 0x8a43e05 0x8a3621d 0x41b49f3 0x2a55b13 0x8ebc474 0x8eb9e4d 0x8eb46ee

[2021-06-02 21:48:58.743777] ERROR [SERVER] init_io (ob_server.cpp:1062) [2755][0][Y0-0000000000000000] [lt=5] [dc=0] init io benchmark fail, (ret=-4027) BACKTRACE:0x90a107e 0x90090c1 0x24c1b14 0x24c176b 0x24c1583 0x24c04f6 0x870573a 0x86fe5c4 0x24be805 0x7f2b97fcc555 0x24bd4e9`
请问是什么原因呢

**Comment by frf12** [comment] 2021-06-04 03:20
Duplicate of #19

**Comment by MizuhaHimuraki** [comment] 2021-06-04 03:21
Duplicate of #19

**Closed by MizuhaHimuraki** 2021-06-04 03:21 UTC
